# Japanese translations for eon.
#
# (c) Copyright 2013-2017 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
msgid ""
msgstr ""
"Project-Id-Version: eon 8.0.0.20\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-03-25 22:18-0600\n"
"PO-Revision-Date: 2014-03-25 22:18-0600\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: ja <LL@li.org>\n"
"Plural-Forms: nplurals=1; plural=0\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: eon/api/middleware/context.py:17
msgid "Role used to identify an authenticated user as administrator."
msgstr "管理者として認証されるユーザーの識別に使用される役割。"

#: eon/api/middleware/context.py:84
msgid "Invalid service catalog json."
msgstr "無効なサービスカタログJSONです。"

#: eon/api/v1/esx_proxy_ip.py:120
#, fuzzy, python-format
msgid "Unable to display the ip details.got the error : %s"
msgstr "vCenter詳細を表示できません。受け取ったエラー: %s"

#: eon/api/v1/esx_proxy_ip.py:135
msgid "Failed to delete. IP associated with esx proxy"
msgstr ""

#: eon/api/v1/esx_proxy_ip_pool.py:29
#, python-format
msgid "'%s' contains whitespace"
msgstr ""

#: eon/api/v1/esx_proxy_ip_pool.py:40
#, python-format
msgid "'%s' is not a valid IP address"
msgstr ""

#: eon/api/v1/esx_proxy_ip_pool.py:54
#, python-format
msgid ""
"Invalid input. '%(target_dict)s' must be a dictionary with keys: "
"%(expected_keys)s"
msgstr ""

#: eon/api/v1/esx_proxy_ip_pool.py:65
#, python-format
msgid ""
"Validation of dictionary's keys failed.Expected keys: %(expected_keys)s "
"Provided keys: %(provided_keys)s"
msgstr ""

#: eon/api/v1/esx_proxy_ip_pool.py:79
#, python-format
msgid "Invalid data format for IP pool: '%s'"
msgstr ""

#: eon/api/v1/esx_proxy_ip_pool.py:105
#, python-format
msgid "Invalid pool type : %(invalid_type)sExpected values : %(expected_values)s"
msgstr ""

#: eon/api/v1/esx_proxy_ip_pool.py:110
#, python-format
msgid "Allocation pool must be empty for '%s' pool type"
msgstr ""

#: eon/api/v1/esx_proxy_ip_pool.py:113
#, python-format
msgid "Allocation pool must have some value for '%s' pool type"
msgstr ""

#: eon/api/v1/esx_proxy_ip_pool.py:220
#, fuzzy, python-format
msgid "Unable to display the ip pool details.got the error : %s"
msgstr "vCenter詳細を表示できません。受け取ったエラー: %s"

#: eon/api/v1/esx_proxy_ip_pool.py:265
msgid "Enter appropriate IP range"
msgstr ""

#: eon/api/v1/managed_entity.py:45
msgid "The maximum number of clusters supported per proxy vm"
msgstr "プロキシVMあたりサポートされるクラスターの最大数"

#: eon/api/v1/managed_entity.py:157
#, python-format
msgid "Unable to display the resource:got the error : %s"
msgstr "リソースを表示できません。受け取ったエラー: %s"

#: eon/api/v1/managed_entity.py:273
#, fuzzy, python-format
msgid "Unable to import the resource  (%(resource_name)s) Got error: %(error)s"
msgstr "リソース (%s) をインポートできません。受け取ったエラー: %s"

#: eon/api/v1/managed_entity.py:330
msgid "Virtual machines are already running on this cluster."
msgstr ""

#: eon/api/v1/managed_entity.py:332
msgid ""
"Virtual machine instances are running on the compute node. Manually "
"remove these instances using the same tools that you used to manage the "
"instances. Instances consume resources and may cause oversubscription "
"when not managed by CloudSystem"
msgstr ""

#: eon/api/v1/managed_entity.py:395
#, python-format
msgid "Cluster '%s' does not have any hosts in connected state"
msgstr ""

#: eon/api/v1/managed_entity.py:397
msgid "Add host to the cluster or reconnect the disconnected hosts"
msgstr ""

#: eon/api/v1/managed_entity.py:402
#, python-format
msgid ""
"Could not determine vShield vApp status on hosts [%(hosts_without_vapp)s]"
" in cluster '%(cluster_name)s'"
msgstr ""

#: eon/api/v1/managed_entity.py:407
msgid "vShield vApp must be installed and running each host of the cluster"
msgstr ""

#: eon/api/v1/managed_entity.py:416
#, python-format
msgid "Could not determine if the cluster '%s' has hosts in connected state"
msgstr ""

#: eon/api/v1/managed_entity.py:438
msgid "Another cluster activation is in progress."
msgstr ""

#: eon/api/v1/managed_entity.py:439
msgid "Wait for the current activation task to complete and try again"
msgstr ""

#: eon/api/v1/managed_entity.py:460
#, fuzzy, python-format
msgid "Could not find Cluster %s"
msgstr "vCenter %s %s を見つけることができませんでした"

#: eon/api/v1/managed_entity.py:461
#, fuzzy, python-format
msgid "Import the cluster"
msgstr "クラスターのプロパティ:%s"

#: eon/api/v1/managed_entity.py:468
#, fuzzy, python-format
msgid "Cluster %s is already activated or in the process of activation"
msgstr "リソース名 %s はすでにアクティブ化されているか、アクティブ化プロセス中です。"

#: eon/api/v1/managed_entity.py:470
msgid ""
"Wait for the current cluster activation task to complete before retrying "
"activation"
msgstr ""

#: eon/api/v1/managed_entity.py:497
#, fuzzy, python-format
msgid ""
"The switch having access to cloud trunk is not configured for the cluster"
" %(cluster_name)s in datacenter %(dc)s"
msgstr "クラスター %s (データセンター %s) のスイッチは構成されていません"

#: eon/api/v1/managed_entity.py:503
msgid "Configure the cloud trunk network switch."
msgstr ""

#: eon/api/v1/managed_entity.py:526
#, python-format
msgid ""
"The cluster '%(cluster_name)s' configuration does not meet the "
"requirements for activation. Errors = %(errors)s"
msgstr ""

#: eon/api/v1/managed_entity.py:531
#, python-format
msgid ""
"The cluster must be DRS enabled, have hosts in connected state, at least "
"one shared datastore and all hosts have access to the switch configured "
"for data trunk networking. The switch '%(switch_name)s' is configured for"
" the datacenter '%(dc)s'"
msgstr ""

#: eon/api/v1/managed_entity.py:584
#, fuzzy, python-format
msgid "Unable to activate the cluster %(cluster_name)s. Internal error occurred"
msgstr "クラスター %s をアクティブ化できません。受け取ったエラー: %s"

#: eon/api/v1/managed_entity.py:667
#, python-format
msgid ""
"Internal error occurred while updating the compute node state in DB. "
"[Error=%s]"
msgstr ""

#: eon/api/v1/managed_entity.py:720 eon/api/v1/managed_entity.py:764
#, fuzzy, python-format
msgid "Unable to activate the cluster %(cluster_name)s Got the error : %(error)s"
msgstr "クラスター %s をアクティブ化できません。受け取ったエラー: %s"

#: eon/api/v1/managed_entity.py:785
msgid "The compute node is activated and cannot be deleted."
msgstr ""

#: eon/api/v1/managed_entity.py:787
msgid "Deactivate the compute node and retry delete."
msgstr ""

#: eon/api/v1/managed_entity.py:812
#, python-format
msgid "Cannot remove resource (%s) in since it is not imported."
msgstr "インポートされていないため、リソース (%s) を削除できません。"

#: eon/api/v1/managed_entity.py:828
#, fuzzy, python-format
msgid ""
"Not deleting the proxy vm. Since there are active resource(s) associated "
"to the proxy (%s)"
msgstr "削除できません! vCenter(%s)に関連付けられたアクティブリソースが存在します"

#: eon/api/v1/managed_entity.py:839
#, fuzzy, python-format
msgid "Could not delete the compute proxy %s"
msgstr "vCenter %sが取得できませんでした"

#: eon/api/v1/managed_entity.py:841
#, python-format
msgid "Delete the proxy vm %s if exists and try to activate again."
msgstr ""

#: eon/api/v1/managed_entity.py:914
msgid "Another cluster deactivation is in progress."
msgstr ""

#: eon/api/v1/managed_entity.py:915
msgid "Wait for the current deactivation task to complete and try again."
msgstr ""

#: eon/api/v1/managed_entity.py:1055
msgid "The deactivation has been initiated."
msgstr ""

#: eon/api/v1/managed_entity.py:1062
#, fuzzy, python-format
msgid "Failed to deactivate cluster. Got error: %s"
msgstr "クラスター %s をアクティブ化できません。受け取ったエラー: %s"

#: eon/api/v1/vcenter.py:205
#, python-format
msgid "Error while listing the vCenters : %s"
msgstr "vCenterをリスト中にエラーが発生しました: %s"

#: eon/api/v1/vcenter.py:279
#, python-format
msgid "Unable to display the vcenter details.got the error : %s"
msgstr "vCenter詳細を表示できません。受け取ったエラー: %s"

#: eon/api/v1/vcenter.py:331
msgid "Registration/update of vCenter failed."
msgstr ""

#: eon/api/v1/vcenter.py:332
msgid ""
"Enter valid vCenter credentials and ensure vCenter is running and is "
"reachable from the appliance"
msgstr ""

#: eon/api/v1/vcenter.py:357
#, python-format
msgid ""
"Failed to register vCenter. The vCenter IP Address (%s) could not be "
"resolved."
msgstr ""

#: eon/api/v1/vcenter.py:370
#, fuzzy, python-format
msgid "Failed to retrieve data for vCenter %s"
msgstr "vCenter %sが取得できませんでした"

#: eon/api/v1/vcenter.py:378
#, python-format
msgid "Failed to register vCenter. vCenter by ip_address (%s) already exists."
msgstr ""

#: eon/api/v1/vcenter.py:404
#, fuzzy, python-format
msgid ""
"There are cluster(s) activated and therefore the vShield credentials "
"cannot be deleted"
msgstr "データセンター %s は別のスイッチ名 (%s) でアクティブ化されたクラスターを持っています。そのため、スイッチ名は変更できません。"

#: eon/api/v1/vcenter.py:419 eon/api/v1/vcenter.py:780
msgid "All vShield credentials must be specified"
msgstr "すべてのvShield認証情報が指定されなければなりません"

#: eon/api/v1/vcenter.py:452
#, python-format
msgid "vCenter with id [%s] does not exist"
msgstr "ID [%s] のvCenterは存在しません"

#: eon/api/v1/vcenter.py:461
#, python-format
msgid "Update of vCenter failed: vCenter ip_address (%s) could not be resolved."
msgstr ""

#: eon/api/v1/vcenter.py:472
#, python-format
msgid "Could not retrieve vCenter %s"
msgstr "vCenter %sが取得できませんでした"

#: eon/api/v1/vcenter.py:482
#, python-format
msgid "Registration/update of vCenter failed: vCenter (%s) already exists."
msgstr ""

#: eon/api/v1/vcenter.py:537
#, fuzzy, python-format
msgid ""
"The datacenter %(dc)s has cluster(s) activated with different switch name"
" (%(switch_details)s) and therefore the switch name cannot be modified"
msgstr "データセンター %s は別のスイッチ名 (%s) でアクティブ化されたクラスターを持っています。そのため、スイッチ名は変更できません。"

#: eon/api/v1/vcenter.py:553
#, fuzzy, python-format
msgid "There are activated/imported clusters(s) associated to the vCenter (ID %s)"
msgstr "削除できません! vCenter(%s)に関連付けられたアクティブリソースが存在します"

#: eon/api/v1/vcenter.py:621
#, python-format
msgid "Error validating vShield credentials : %s"
msgstr "vShield認証情報を検証中にエラーが発生しました: %s"

#: eon/api/v1/vcenter.py:622
#, fuzzy
msgid "Enter valid credentials"
msgstr "vShield認証情報を検証できませんでした"

#: eon/api/v1/vcenter.py:629
#, fuzzy, python-format
msgid "vShield IP %(ip_address)s is invalid for vCenter %(vcenter_ip)s "
msgstr "vShield IP %s (vCenter %s) が無効です "

#: eon/api/v1/vcenter.py:633
msgid "Enter valid VShield IP address"
msgstr ""

#: eon/api/v1/vcenter.py:830 eon/api/v1/vcenter.py:840
#, fuzzy, python-format
msgid "Registering of VCenter failed. Got error: '%s'"
msgstr "vCenterの登録中、コンテキスト:%s"

#: eon/api/v1/vcenter.py:967 eon/api/v1/vcenter.py:976
#, python-format
msgid "Failed to update vCenter. Got error: %s"
msgstr "vCenterのアップデートに失敗しました。受け取ったエラー: %s"

#: eon/api/v1/vcenter.py:1027
#, fuzzy, python-format
msgid "Failed to unregister vCenter.Got error: %s"
msgstr "vCenterのアップデートに失敗しました。受け取ったエラー: %s"

#: eon/api/v1/vcenter.py:1035
#, fuzzy, python-format
msgid "Failed to unregister vCenter. Got error: %s"
msgstr "vCenterのアップデートに失敗しました。受け取ったエラー: %s"

#: eon/common/config.py:24
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:isc-api-keystone] use the value \"keystone\""
msgstr ""
"サービス名を持ったペースト構成ファイル内のパイプラインの不完全な名前は削除されました。例えば、ペーストセクション名が値 \"keystone\" "
"を使用する[pipeline:isc-api-keystone]の場合です。"

#: eon/common/config.py:30
msgid "Name of the paste configuration file."
msgstr "ペースト構成ファイルの名前。"

#: eon/common/config.py:34
msgid "Python module path of data access API"
msgstr "データアクセスAPIのPythonモジュールパス"

#: eon/common/config.py:36
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr "リクエスト内で明確に指定されていない場合、リクエストによって返されるアイテム数のデフォルト値。"

#: eon/common/config.py:39
msgid "Maximum permissible number of items that could be returned by a request"
msgstr "リクエストによって返されるアイテムの許可される最大数"

#: eon/common/config.py:42
msgid "Deploy the v1 OpenStack Images API. "
msgstr "v1 OpenStackイメージAPIの展開。 "

#: eon/common/config.py:44
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr "デバッグ接続をリスンしているpydevプロセスのホスト名/IP"

#: eon/common/config.py:47
msgid "The port on which a pydev process is listening for connections."
msgstr "pydevプロセスが接続をリスンしているポート。"

#: eon/common/config.py:50
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr "レジストリまたはデータベースとの通信中、センシティブなメタデータの暗号化に使用されるキー"

#: eon/common/config.py:78
#, python-format
msgid "Unable to locate specified logging config file: %s"
msgstr ""

#: eon/common/config.py:96
msgid "Invalid syslog facility"
msgstr "無効なsyslogファシリティです"

#: eon/common/config.py:134
#, fuzzy, python-format
msgid "Unable to locate paste config file for %s."
msgstr "ペースト構成ファイルの名前。"

#: eon/common/config.py:172
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""
"%(app_name)s を構成ファイル %(conf_file)s からロードできません。\n"
"受け取ったエラー: %(e)r"

#: eon/common/exception.py:25
msgid "An unknown exception occurred"
msgstr "不明な例外が発生しました"

#: eon/common/exception.py:50
msgid "Missing required argument."
msgstr "必要な引数が見つかりません。"

#: eon/common/exception.py:54
#, python-format
msgid "Missing required credential: %(required)s"
msgstr "必要な認証情報がみつかりません:%(required)s"

#: eon/common/exception.py:58
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr "認証ストラテジが正しくありません。\"%(expected)s\" が予想されましたが、\"%(received)s\" を受け取りました。"

#: eon/common/exception.py:63
msgid "An object with the specified identifier was not found."
msgstr "指定された識別子を持つオブジェクトが見つかりませんでした。"

#: eon/common/exception.py:67
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr "URIで不明なスキーマ '%(scheme)s' が見つかりました"

#: eon/common/exception.py:71
msgid "The Store URI was malformed."
msgstr "ストアURIはフォームが正しくありません。"

#: eon/common/exception.py:75
msgid "An object with the same identifier already exists."
msgstr "同じ識別子を持つオブジェクトがすでに存在します。"

#: eon/common/exception.py:79
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr "URL %(url)s で認証サービスへの接続エラー/バッドリクエストが発生しました。"

#: eon/common/exception.py:83
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr "URL %(url)s で認証サービスが見つかりません。"

#: eon/common/exception.py:87
msgid "Authorization failed."
msgstr "認証は失敗しました。"

#: eon/common/exception.py:91
msgid "You are not authenticated."
msgstr "認証されていません。"

#: eon/common/exception.py:95 eon/common/exception.py:100
msgid "You are not authorized to complete this action."
msgstr "このアクションを完了するための認証が行われていません。"

#: eon/common/exception.py:104
msgid "Data supplied was not valid."
msgstr "提供されたデータが無効でした。"

#: eon/common/exception.py:108
msgid "Sort key supplied was not valid."
msgstr "提供されたソートキーが無効でした。"

#: eon/common/exception.py:112
msgid "Unable to filter using the specified range."
msgstr "指定された範囲を使用してフィルターできません。"

#: eon/common/exception.py:116
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr "属性 '%(property)s' は読み取り専用です。"

#: eon/common/exception.py:120
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr "属性 '%(property)s' は予約されています。"

#: eon/common/exception.py:124
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr "認証のため %(uri)s へリダイレクト中です。"

#: eon/common/exception.py:128
msgid "There was an error migrating the database."
msgstr "データベースの移行中にエラーが発生しました。"

#: eon/common/exception.py:132
msgid "There was an error connecting to a server"
msgstr "サーバーに接続中にエラーが発生しました。"

#: eon/common/exception.py:136
msgid "There was an error configuring the client."
msgstr "クライアントの構成中にエラーが発生しました。"

#: eon/common/exception.py:140
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""
"リクエストは302 Multiple "
"Choicesを返しました。これは一般的に、リクエストURI内にバージョンインジケーターが含まれていなかったことを意味します。\n"
"\n"
"返された応答のボディ: \n"
"%(body)s"

#: eon/common/exception.py:146
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"リクエストは413 Request Entity Too "
"Largeを返しました。これは一般的に、範囲制限またはクォータしきい値が破られたことを意味します。\n"
"\n"
"応答のボディ: \n"
"%(body)s"

#: eon/common/exception.py:157
#, fuzzy
msgid ""
"The request returned 503 Service Unavailable. This generally occurs on "
"service overload or other transient outage."
msgstr "リクエストは503 Service Unavailableを返しました。これは一般的に、サーバーが過負荷またはその他の一時的な停止で発生します。"

#: eon/common/exception.py:168
msgid "The request returned 500 Internal Server Error."
msgstr "リクエストは500 Internal Server Errorを返しました。"

#: eon/common/exception.py:172
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"リクエストは予期しないステータスを返しました:%(status)s。\n"
"\n"
"応答のボディ: \n"
"%(body)s"

#: eon/common/exception.py:177
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr "コンテンツタイプ %(content_type)s が無効です"

#: eon/common/exception.py:181
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr "APIサーバー上でレジストリが正しく構成されていませんでした。理由:%(reason)s"

#: eon/common/exception.py:186
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr "ストア %(store_name)s は正しく構成できませんでした。理由:%(reason)s"

#: eon/common/exception.py:191
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr "ドライバー %(driver_name)s は正しく構成できませんでした。理由:%(reason)s"

#: eon/common/exception.py:196
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr "最大リダイレクト (%(redirects)s) を超えました。"

#: eon/common/exception.py:200 eon/pavmm/utils.py:442
msgid "Error in generating the required certs for compute"
msgstr ""

#: eon/common/exception.py:204
msgid "Received invalid HTTP redirect."
msgstr "無効なHTTPリダイレクトを受け取りました。"

#: eon/common/exception.py:208
msgid "Response from Keystone does not contain a isc endpoint."
msgstr "キーストーンからの応答がiscエンドポイントを含んでいません。"

#: eon/common/exception.py:212
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr "サーバーワーカー作成が失敗しました: %(reason)s。"

#: eon/common/exception.py:216
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr "スキーマをロードできません: %(reason)s"

#: eon/common/exception.py:220
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr "提供されたオブジェクトはスキーマ '%(schema)s' と一致しません: %(reason)s"

#: eon/common/exception.py:225
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr "提供されたヘッダー機能はサポートされません: %(feature)s"

#: eon/common/exception.py:229
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr "%(cls)s 例外が最後のrpcコールで発生しました: %(val)s"

#: eon/common/exception.py:233 eon/common/exception.py:237
#, python-format
msgid "%(reason)s"
msgstr ""

#: eon/common/exception.py:246
#, python-format
msgid "Unable to store password: %(status)s"
msgstr ""

#: eon/common/exception.py:250
#, python-format
msgid "Unable to fetch password: %(status)s"
msgstr ""

#: eon/common/exception.py:259
#, python-format
msgid "The cluster could not be deactivated as a compute resource : %(reason)s"
msgstr ""

#: eon/common/exception.py:264
#, fuzzy, python-format
msgid "The cluster activation Failed : %(reason)s"
msgstr "サーバーワーカー作成が失敗しました: %(reason)s。"

#: eon/common/exception.py:313
msgid "Invalid Operation"
msgstr ""

#: eon/common/exception.py:322
msgid "Failed to upgrade Proxy."
msgstr ""

#: eon/common/exception.py:331
#, python-format
msgid "Database error has occurred [%(reason)s]."
msgstr ""

#: eon/common/exception.py:335
#, python-format
msgid "Proxy VM has errors: %(reason)s"
msgstr ""

#: eon/common/log.py:88
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "非推奨構成の致命的なコール: %(msg)s"

#: eon/common/messageutils.py:69
msgid "Exception in . Retry                     counter:"
msgstr ""

#: eon/common/messageutils.py:78
#, python-format
msgid "Initiating status check on proxy %s"
msgstr ""

#: eon/common/utils.py:90
msgid "Token is not specified or is not valid"
msgstr "トークンが指定されていないか、無効です。"

#: eon/common/utils.py:145
msgid "SDN controller is not up / agent services are not running Trying again..."
msgstr ""

#: eon/common/utils.py:180
msgid "Checking the proxy vm status..."
msgstr ""

#: eon/common/utils.py:184
#, python-format
msgid "%s consumer is not responding"
msgstr ""

#: eon/common/utils.py:222 eon/common/utils.py:253
msgid "Can not get token/tenant id for the REST API"
msgstr ""

#: eon/common/utils.py:229
#, python-format
msgid "Unable to do %s. The cluster could not be updated."
msgstr ""

#: eon/common/utils.py:241
msgid "SDN agents are not running / not responding"
msgstr ""

#: eon/common/utils.py:245
#, python-format
msgid "The cluster %s has been successful."
msgstr ""

#: eon/common/utils.py:260
#, fuzzy, python-format
msgid "Unable to deactivate the cluster %s from the compute service."
msgstr "クラスター %s をアクティブ化できません。受け取ったエラー: %s"

#: eon/common/utils.py:263
#, python-format
msgid "Cluster %s Successfully removed from the compute service"
msgstr ""

#: eon/common/utils.py:386
#, fuzzy, python-format
msgid "Checking the Rabbitmq server status %s"
msgstr "RabbitMQサーバーのホスト名"

#: eon/common/utils.py:389
msgid "Listing rabbitmq proxy users"
msgstr ""

#: eon/common/utils.py:392
#, python-format
msgid "The Rabbitmq server status %s"
msgstr ""

#: eon/common/utils.py:393
#, python-format
msgid "The rabbitmq proxy users %s"
msgstr ""

#: eon/common/utils.py:394
#, python-format
msgid "Listing the states of the nova services %s"
msgstr ""

#: eon/common/utils.py:397
#, python-format
msgid "Appliance-proxy state is improper. Got the exception%s"
msgstr ""

#: eon/common/utils.py:426
#, python-format
msgid ""
"Error validating vShield App configuration on the hosts of the cluster. "
"Error detail: %s"
msgstr ""

#: eon/common/utils.py:428
msgid ""
"Verify is the vShield manager is running and is accessible. vSheild "
"manager is used to determine if vApp is running on the hosts of the "
"cluster"
msgstr ""

#: eon/common/wsgi.py:39
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr "サーバーをバインドするためのアドレス。特定のネットワークインターフェースを選択する場合に、役立ちます。"

#: eon/common/wsgi.py:42
msgid "The port on which the server will listen."
msgstr "サーバーがリスンするポート。"

#: eon/common/wsgi.py:47
msgid "The backlog value that will be used when creating the TCP listener socket."
msgstr "TCPリスナーソケットを作成する場合に使用されるバックログ値。"

#: eon/common/wsgi.py:50
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This isthe time in seconds"
" that the connection must be idle before TCP starts sending keepalive "
"probes."
msgstr "ソケットオプションTCP_KEEPIDLEの値。これはTCPがキープアライブ調査を送り始める前に、接続がアイドル状態でなければならない時間(秒)です。"

#: eon/common/wsgi.py:53
msgid "CA certificate file to use to verify connecting clients."
msgstr "クライアント接続の確認に使用されるCA証明書ファイル。"

#: eon/common/wsgi.py:55
msgid "Certificate file to use when starting API server securely."
msgstr "APIサーバーを安全に開始する場合に使用される証明書ファイル。"

#: eon/common/wsgi.py:57
msgid "Private key file to use when starting API server securely."
msgstr "APIサーバーを安全に開始する場合に使用される秘密キーファイル"

#: eon/common/wsgi.py:62
msgid ""
"The number of child process workers that will be created to service API "
"requests."
msgstr "APIリクエストのサービスに作成される子プロセスワーカー数。"

#: eon/common/wsgi.py:164
msgid "You must implement __call__"
msgstr ""

#: eon/common/wsgi.py:219
#, python-format
msgid "Loading %(app_name)s from %(conf_file)s"
msgstr "%(app_name)s を %(conf_file)s からロード中です"

#: eon/common/wsgi.py:318
msgid "Malformed JSON in request body."
msgstr "リクエストボディ内に不正な形式のJSONです。"

#: eon/db/sqlalchemy/api.py:41
msgid ""
"Period in seconds after which SQLAlchemy should reestablish its "
"connection to the database."
msgstr "SQLAlchemyがデータベースとの接続を再確立しなければならない期間(秒)。"

#: eon/db/sqlalchemy/api.py:44
msgid "The number of times to retry a connection to the SQLserver."
msgstr "SQLサーバーへの接続を再試行する回数。"

#: eon/db/sqlalchemy/api.py:47
msgid ""
"The amount of time to wait (in seconds) before attempting to retry the "
"SQL connection."
msgstr "SQL接続の再試行を試みるまでに待機する時間(秒)。"

#: eon/db/sqlalchemy/api.py:50
msgid "A boolean that determines if the database will be automatically created."
msgstr "データベースが自動的に作成されるかどうかを決定するブーリアン。"

#: eon/db/sqlalchemy/api.py:144
#, python-format
msgid ""
"Error configuring registry database with supplied sql_connection. Got "
"error: %s"
msgstr "提供されたSQL接続でレジストリデーターベースを構成中にエラーが発生しました。受け取ったエラー: %s"

#: eon/db/sqlalchemy/api.py:313 eon/tests/unit/db/simple/api.py:548
#, python-format
msgid "No vCenter found with ID %s"
msgstr "ID %s のvCenterが見つかりませんでした"

#: eon/db/sqlalchemy/api.py:428 eon/tests/unit/db/simple/api.py:407
msgid "IP is in use. Can't delete it"
msgstr ""

#: eon/db/sqlalchemy/api.py:456 eon/tests/unit/db/simple/api.py:219
#: eon/tests/unit/db/simple/api.py:225
#, fuzzy, python-format
msgid "No ESX Proxy IP found with ID %s"
msgstr "ID %s のvCenterが見つかりませんでした"

#: eon/db/sqlalchemy/api.py:530
#, fuzzy, python-format
msgid "IP %s already exists!"
msgstr "名前(%s)のESXプロキシはすでに存在します"

#: eon/db/sqlalchemy/api.py:591 eon/tests/unit/db/simple/api.py:312
#: eon/tests/unit/db/simple/api.py:319
#, python-format
msgid "No ESX Proxy IP Pool found with ID %s"
msgstr ""

#: eon/db/sqlalchemy/api.py:628 eon/tests/unit/db/simple/api.py:372
msgid "Can't change pool type.IP already in use."
msgstr ""

#: eon/db/sqlalchemy/api.py:655
msgid "Unable to create ippool"
msgstr ""

#: eon/db/sqlalchemy/api.py:672
#, python-format
msgid "IP %s assign to %s."
msgstr ""

#: eon/db/sqlalchemy/api.py:680
msgid "No IPs found."
msgstr ""

#: eon/db/sqlalchemy/api.py:682
msgid "No free IP."
msgstr ""

#: eon/db/sqlalchemy/api.py:712
#, python-format
msgid "No IP assign to %s."
msgstr ""

#: eon/db/sqlalchemy/api.py:728 eon/db/sqlalchemy/api.py:763
#, fuzzy
msgid "Resource-Entity ID already exists!"
msgstr "識別子を持つvCenterはすでに存在します!"

#: eon/db/sqlalchemy/api.py:800 eon/tests/unit/db/simple/api.py:682
#, fuzzy, python-format
msgid "No Resource found with ID %s"
msgstr "ID %s のvCenterが見つかりませんでした"

#: eon/db/sqlalchemy/api.py:869 eon/db/sqlalchemy/api.py:905
#, fuzzy
msgid "ESX_PROXY ID already exists!"
msgstr "識別子を持つESXプロキシはすでに存在します!"

#: eon/db/sqlalchemy/api.py:949
#, python-format
msgid "No Esx-Proxy found (ID %s)"
msgstr ""

#: eon/db/sqlalchemy/api.py:976
#, fuzzy, python-format
msgid "No Esx-Proxy found with name %s "
msgstr "ID %s のvCenterが見つかりませんでした"

#: eon/db/sqlalchemy/api.py:1061
#, fuzzy, python-format
msgid "vCenter ID %s already exists!"
msgstr "識別子を持つvCenterはすでに存在します!"

#: eon/db/sqlalchemy/api.py:1175
#, python-format
msgid "Could not update property %s for resource %s"
msgstr ""

#: eon/db/sqlalchemy/migration.py:36
msgid "database is not under migration control"
msgstr "データベースは、移行コントロール中でありません"

#: eon/db/sqlalchemy/migration.py:76
msgid "database is already under migration control"
msgstr "データベースは、すでに移行コントロール中です"

#: eon/pavmm/utils.py:123
#, fuzzy, python-format
msgid "Creating proxy: %s"
msgstr "プロパティ %s %s を削除中です"

#: eon/pavmm/utils.py:148
#, python-format
msgid "Starting the proxy: %s"
msgstr ""

#: eon/pavmm/utils.py:166
#, fuzzy, python-format
msgid "Deleting proxy %s:"
msgstr "プロパティ %s %s を削除中です"

#: eon/pavmm/utils.py:212
#, python-format
msgid "Generating certificates for Compute Proxy %s"
msgstr ""

#: eon/pavmm/utils.py:233
msgid "IP address for Proxy Appliance not available."
msgstr ""

#: eon/pavmm/utils.py:234
msgid "Set IPs (DHCP/Static) for vCenter Proxy Appliance"
msgstr ""

#: eon/pavmm/utils.py:350
msgid "Failed to copy the certificates"
msgstr ""

#: eon/pavmm/utils.py:352
#, python-format
msgid "Generating certificates for Compute Proxy %s completed"
msgstr ""

#: eon/pavmm/utils.py:395
#, python-format
msgid "Deleting certificates for the VM Proxy %s"
msgstr ""

#: eon/pavmm/utils.py:463
#, python-format
msgid "Unable to create Compute Proxy Appliance. %s"
msgstr ""

#: eon/pavmm/utils.py:481
#, python-format
msgid "Failed to Power-ON the proxy Appliance. %s"
msgstr ""

#: eon/pavmm/utils.py:490
#, python-format
msgid "Starting Proxy VM %s upgrade.hostname"
msgstr ""

#: eon/pavmm/utils.py:491
msgid "Waiting for the proxy to upgrade."
msgstr ""

#: eon/pavmm/utils.py:502
#, fuzzy, python-format
msgid "Proxy VM %s upgrade successfully completed.hostname"
msgstr "ESXプロキシ VM %s は正常に作成されました "

#: eon/pavmm/utils.py:507 eon/pavmm/utils.py:512
#, python-format
msgid "Failed to upgrade Proxy VM %shostname"
msgstr ""

#: eon/pavmm/utils.py:522
msgid "Waiting for the nova compute service to start"
msgstr ""

#: eon/pavmm/utils.py:537
#, fuzzy, python-format
msgid "Nova compute service has started sucessfully"
msgstr "Novaコンピュートノードの開始に失敗しました。エラー: %(status)s"

#: eon/pavmm/utils.py:550
#, fuzzy, python-format
msgid "Nova compute service failed to start"
msgstr "Novaコンピュートノードの開始に失敗しました。エラー: %(status)s"

#: eon/pavmm/utils.py:551
msgid ""
"If DHCP is selected for vCenter proxy VM, ensure that DHCP service is "
"running on the network. If static IP is selected, then ensure that the "
"free IPs in the pool are not already in use."
msgstr ""

#: eon/tests/unit/db/simple/api.py:259
#, python-format
msgid "IP %s already exists!ipaddress"
msgstr ""

#: eon/tests/unit/vmware/fake_vmware_api.py:118
#, python-format
msgid "Property %(attr)s not set for the managed object %(name)s"
msgstr ""

#: eon/tests/unit/vmware/fake_vmware_api.py:408
#, python-format
msgid "Logging out a session that is invalid or already logged out: %s"
msgstr ""

#: eon/tests/unit/vmware/fake_vmware_api.py:425
msgid "Session Invalid"
msgstr ""

#: eon/vmware/cluster_validate.py:77
msgid "No shared datastore available in the cluster"
msgstr ""

#: eon/vmware/cluster_validate.py:87
msgid "Cluster DRS not enabled"
msgstr ""

#: eon/vmware/inventory_collector.py:67
#, python-format
msgid "Exception occurred while monitoring updates on vCenter got the error : %s"
msgstr ""

#: eon/vmware/inventory_collector.py:198
#, python-format
msgid "Could not validate cluster configuration. Internal error: %s"
msgstr ""

#: eon/vmware/inventory_collector.py:247
msgid "No switches configured on the host"
msgstr ""

#: eon/vmware/inventory_collector.py:267
#, python-format
msgid "Hosts %s in the cluster do not have vSwitch '%s'"
msgstr ""

#: eon/vmware/inventory_collector.py:324
#, python-format
msgid "Hosts %s in the cluster do not have access to the dvSwitch"
msgstr ""

#: eon/vmware/inventory_collector.py:334
#, python-format
msgid ""
"The switch with name '%s' is configured as the data networking access "
"switch for this datacenter and the hosts in the cluster are not connected"
" to this switch"
msgstr ""

#: eon/vmware/inventory_collector.py:421
#, python-format
msgid "Update received on vCenter %s for MOR %s with property %s and type %s"
msgstr ""

#: eon/vmware/inventory_collector.py:439
#, python-format
msgid ""
"Delete event received on vCenter %(vcenter) for MOR "
"%(mor)vcenterip_address"
msgstr ""

#: eon/vmware/vim.py:121
#, python-format
msgid "Unable to validate session %s!"
msgstr ""

#: eon/vmware/vim_session.py:100
#, python-format
msgid "Could not find (%s) in VIM Object"
msgstr ""

#: eon/vmware/vim_session.py:115
#, python-format
msgid "Task : %s (%s) status: success"
msgstr ""

#: eon/vmware/vim_session.py:120
#, python-format
msgid "Task : %s (%s) status: error, cause: %s"
msgstr ""

#: eon/vmware/vim_util.py:61
msgid "urllib2 error "
msgstr ""

#: eon/vmware/vim_util.py:67
msgid "urllib2 error : "
msgstr ""

#: eon/vmware/vim_util.py:81
msgid "Socket timeout"
msgstr ""

#: eon/vmware/vim_util.py:94
msgid "Exception"
msgstr ""

#: eon/vmware/vim_util.py:105
#, python-format
msgid "Error(s) %s occurred in the call to RetrieveProperties"
msgstr ""

#: eon/vmware/vshield_client.py:73
#, python-format
msgid "Error in connecting to vShield manager %s"
msgstr ""

#: eon/vmware/vshield_client.py:76
#, python-format
msgid "An error occurred while executing vShield API: %s"
msgstr ""

#: eon/vmware/vshield_client.py:85
#, fuzzy
msgid "Could not validate vShield credentials"
msgstr "vShield認証情報を検証できませんでした"

#~ msgid "Unable to retrieve request id from context"
#~ msgstr "コンテキストからリクエストIDを取得できません"

#~ msgid "Determining version of request: %(method)s %(path)s Accept: %(accept)s"
#~ msgstr "リクエストのバージョンを確認中です: %(method)s %(path)s 許可: %(accept)s"

#~ msgid "Using url versioning"
#~ msgstr "URLバージョン化を使用中です"

#~ msgid "Unknown version. Returning version choices."
#~ msgstr "不明なバージョン。バージョン選択肢を返しています。"

#~ msgid "Matched version: v%d"
#~ msgstr "一致したバージョン: v%d"

#~ msgid "Validating required attributes...Got: %s, Required attributes: %s"
#~ msgstr "必要な属性の検証中... 受け取った:%s、必要な属性:%s"

#~ msgid "Fetching list of all registered ESX-Proxy"
#~ msgstr "すべての登録済みESXプロキシのリストをフェッチ中です"

#~ msgid "Validating ESX-Proxy before creating, ESX-Proxy: %s"
#~ msgstr "作成前にESXプロキシの検証中、ESXプロキシ:%s"

#~ msgid "ESX-Proxy by name (%s) not found"
#~ msgstr "名前(%s)のESXプロキシが見つかりません"

#~ msgid "Validating ESX-Proxy before updating, ESX-Proxy id: %s"
#~ msgstr "アップデート前にESXプロキシの検証中、ESXプロキシ ID:%s"

#~ msgid "Validating ESX-Proxy(id: %s) before deleting"
#~ msgstr "削除前に ESXプロキシ(ID: %s)の検証中"

#~ msgid "Failed to delete %s"
#~ msgstr "%s の削除に失敗しました"

#~ msgid "Registering ESX-Proxy, context: %s, ESX-Proxy data: %s"
#~ msgstr "ESXプロキシの登録中、コンテキスト:%s、ESXプロキシデータ:%s"

#~ msgid "Required attributes validation failed: %s"
#~ msgstr "必要な属性の確認に失敗しました:%s"

#~ msgid "Cannot create ESX-Proxy reason: %s"
#~ msgstr "ESXプロキシを作成できません。理由:%s"

#~ msgid "Successfully created esx_proxy"
#~ msgstr "ESXプロキシは正常に作成されました"

#~ msgid "Failed to add esx_proxy metadata. Got error: %(e)s"
#~ msgstr "ESXプロキシ メタデータの追加に失敗しました。受け取ったエラー: %(e)s"

#~ msgid "Updating ESX-Proxy, context: %s"
#~ msgstr "ESXプロキシのアップデート中、コンテキスト:%s"

#~ msgid "ESX-Proxy data: %s"
#~ msgstr "ESXプロキシデータ:%s"

#~ msgid "Required attribute validation failed: %s"
#~ msgstr "必要な属性の確認に失敗しました:%s"

#~ msgid "Cannot update ESX-Proxy(ID: %s) reason: %s"
#~ msgstr "ESXプロキシ(ID: %s)をアップデートできません 理由: %s"

#~ msgid "Successfully updated esx_proxy"
#~ msgstr "ESXプロキシは正常にアップデートされました"

#~ msgid "Failed to update vCenter. Got error: %(e)s"
#~ msgstr "vCenterのアップデートに失敗しました。受け取ったエラー: %(e)s"

#~ msgid "Deleting ESX-Proxy, context: %s id: %s"
#~ msgstr "ESXプロキシの削除中、コンテキスト:%s ID:%s"

#~ msgid "Cannot delete ESX-Proxy(ID: %s) reason: %s"
#~ msgstr "ESXプロキシ(ID: %s)を削除できません 理由: %s"

#~ msgid "Successfully destroyed esx_proxy"
#~ msgstr "ESXプロキシは正常に破棄されました"

#~ msgid "Failed to delete esx_proxy. Got error: %(e)s"
#~ msgstr "ESXプロキシの削除に失敗しました。受け取ったエラー: %(e)s"

#~ msgid "Store for scheme %s not found"
#~ msgstr "スキーム %s のストアが見つかりません"

#~ msgid "Unable to display the resources:got the error : %s"
#~ msgstr "リソースを表示できません。受け取ったエラー: %s"

#~ msgid "Registering resource, context: %s, vCenter: %s, Resource: %s"
#~ msgstr "リソースの登録中、コンテキスト:%s、vCenter:%s、リソース:%s"

#~ msgid "Checking if max supported clusters limit reached"
#~ msgstr "サポートされるクラスターの最大数に達していないか確認中です"

#~ msgid "Max supported clusters limit reached, Creating"
#~ msgstr "サポートされるクラスターの最大数に達しました、作成中"

#~ msgid "Using existing ESX-Proxy: %s"
#~ msgstr "既存のESXプロキシを使用しています:%s"

#~ msgid "state_change for resource: %s state = %s"
#~ msgstr "リソースの状態変化: %s 状態 = %s"

#~ msgid "Import resource %s "
#~ msgstr "リソース %s のインポート "

#~ msgid "Imported resource %s and imported id is %s"
#~ msgstr "インポートされたリソース %s およびインポートされたIDは %s です"

#~ msgid "Imported resource %s and sending response %s"
#~ msgstr "インポートされたリソース %s および応答 %s を送信しています"

#~ msgid "Import resource information passed is %s"
#~ msgstr "渡されたインポートリソース情報は %s です"

#~ msgid "Resource name %s is already importedresource_name"
#~ msgstr "リソース名 %s はすでにimportedresource_nameです"

#~ msgid "Resource name %s is not imported"
#~ msgstr "リソース名 %s はインポートされません"

#~ msgid "Found imported resource %s"
#~ msgstr "インポートされたリソース %s が見つかりました"

#~ msgid "Found valid imported resource %s"
#~ msgstr "有効なインポートされたリソース %s が見つかりました"

#~ msgid "DC for resource %s is %s"
#~ msgstr "リソース %s のDCは %s です"

#~ msgid "cluster data = %s"
#~ msgstr "クラスターデータ = %s"

#~ msgid ""
#~ "Switch %s has configuration errors for"
#~ " the cluster %s in datacenter %s. "
#~ "Errors = %s"
#~ msgstr "スイッチ %s (クラスター %s  - データセンター %s) に構成エラーがあります。 エラー = %s"

#~ msgid " Resource entity details: %s "
#~ msgstr " リソースエンティティ詳細: %s "

#~ msgid "remove_resource %s %s %s"
#~ msgstr "remove_resource %s %s %s"

#~ msgid "Removed resource %s and sending response %s"
#~ msgstr "削除されたリソース %s および応答 %s を送信しています"

#~ msgid "Un-Registering resource id: %s"
#~ msgstr "登録されていないリソースID:%s"

#~ msgid "Successfully unregistered resource [%s]"
#~ msgstr "リソース [%s] は正常に登録解除されました"

#~ msgid "Unable to unregister resource %sGot error: %s"
#~ msgstr "リソース %s を登録解除できません。受け取ったエラー: %s"

#~ msgid "Successfully destroyed resource_entity"
#~ msgstr "resource_entityは正常に破棄されました"

#~ msgid "Failed to delete vCenter. Got error: %(e)s"
#~ msgstr "vCenterの削除に失敗しました。受け取ったエラー: %(e)s"

#~ msgid "ManagedEntitySerializer"
#~ msgstr "管理エンティティシリアライザー"

#~ msgid "Fetching list of all registered vcenters"
#~ msgstr "すべての登録済みvCenterのリストをフェッチ中です"

#~ msgid "Unable to list the details of vCenter,Got error %s"
#~ msgstr "vCenterの詳細をリストできません。受け取ったエラー: %s"

#~ msgid "Details of vcenter:  %s has been returned"
#~ msgstr "vCetnerの詳細: %s が返されました"

#~ msgid "ip_address"
#~ msgstr "ip_address"

#~ msgid ""
#~ "Registration of vCenter failed.\n"
#~ "This could be due to invalid "
#~ "credentials or the vCenter server %s "
#~ "is unreachable.ip_address"
#~ msgstr ""
#~ "vCenterの登録が失敗しました。\n"
#~ "これは原因として無効な認証情報またはvCenterサーバー %s がunreachable.ip_addressである可能性があります。"

#~ msgid "vCenter with id (%s) does not exist"
#~ msgstr "ID (%s) のvCenterは存在しません"

#~ msgid "Check vCenter connectivity since IP has changed old IP = %s new IP = %s"
#~ msgstr "IPが変更されたため、vCenterの接続性を確認してください。古いIP = %s 新しいIP = %s"

#~ msgid "Configured settings = %s"
#~ msgstr "設定構成中 = %s"

#~ msgid ""
#~ "Fail to delete, there are active "
#~ "Resource(s) associated to vCenter (ID "
#~ "%s)"
#~ msgstr "削除に失敗しました。vCenter(ID %s)に関連付けられたアクティブリソースが存在します"

#~ msgid "The list of proxy associated to the vCenter %s"
#~ msgstr "vCenter %s に関連付けられたプロキシのリスト"

#~ msgid "Fetch all resources associated to ESX-Proxy(ID: %s)"
#~ msgstr "ESXプロキシ(ID: %s) に関連付けられたすべてのリソースをフェッチ"

#~ msgid "Returning...Resource-Name: %s, Resource-Path: %s"
#~ msgstr "応答...リソース名: %s、リソースパス: %s"

#~ msgid "Required attributes %s"
#~ msgstr "属性 %s は必須です"

#~ msgid "Successfully added the vcenter %s"
#~ msgstr "vCenter %s は正常に追加されました"

#~ msgid "Unable to display the vcenter details:got the error : %s"
#~ msgstr "vCenter詳細を表示できません。受け取ったエラー: %s"

#~ msgid "Updating vcenter, context: %s"
#~ msgstr "vCenterのアップデート中、コンテキスト:%s"

#~ msgid "vCenter-Data: name: %s, username: %s, ip_address: %s, port: %s"
#~ msgstr "vCenterデータ: 名前:%s、ユーザー名:%s、IPアドレス:%s、ポート:%s"

#~ msgid "Reconfigured switch settings = %s"
#~ msgstr "再構成されたスイッチ設定 = %s"

#~ msgid "Updating settings = %s"
#~ msgstr "設定のアップデート中 = %s"

#~ msgid "Successfully updated vcenter settings"
#~ msgstr "vCenter設定は正常にアップデートされました"

#~ msgid "Response for update vCenter %s"
#~ msgstr "vCenter %s アップデートの応答"

#~ msgid "Unregister vcenter id: %s"
#~ msgstr "登録されていないvCenter ID:%s"

#~ msgid "Successfully deleted vcenter"
#~ msgstr "vCenterは正常に削除されました"

#~ msgid "Failed to delete vCenter. Got error: %s"
#~ msgstr "vCenterの削除に失敗しました。受け取ったエラー: %s"

#~ msgid "PAVMM Create VM REST api return error: %(status)s"
#~ msgstr "PAVMM作成VM REST APIリターンエラー: %(status)s"

#~ msgid "PAVMM Start VM REST api return error: %(status)s"
#~ msgstr "PAVMM開始VM REST APIリターンエラー: %(status)s"

#~ msgid "PAVMM Delete VM REST api return error: %(status)s"
#~ msgstr "PAVMM削除VM REST APIリターンエラー: %(status)s"

#~ msgid "Max serialization depth exceeded on object: %d %s"
#~ msgstr "最大シリアライゼーション深さをオブジェクトで超えました:%d %s"

#~ msgid "Deprecated: %s"
#~ msgstr "非推奨:%s"

#~ msgid "syslog facility must be one of: %s"
#~ msgstr "Syslogファシリティは次のひとつでなければなりません:%s"

#~ msgid "Request must be a list of commands"
#~ msgstr "リクエストはコマンドのリストでなければなりません"

#~ msgid "Bad Command: %s"
#~ msgstr "誤ったコマンド:%s"

#~ msgid "Wrong command structure: %s"
#~ msgstr "間違ったコマンド構造:%s"

#~ msgid "Command not found"
#~ msgstr "コマンドが見つかりません"

#~ msgid ""
#~ "RPC Call Error: %(val)s\n"
#~ "%(tb)s"
#~ msgstr ""
#~ "RPCコールエラー:%(val)s\n"
#~ "%(tb)s"

#~ msgid "Read-only access"
#~ msgstr "読み取り専用アクセス"

#~ msgid "Invalid backend: %s"
#~ msgstr "無効なバックエンド:%s"

#~ msgid "The authorization key is not present"
#~ msgstr "認証キーが存在しません"

#~ msgid "Authorization token is empty or not present"
#~ msgstr "認証トークンが空か、存在しません。"

#~ msgid "Authorization check response is %s"
#~ msgstr "認証チェック応答は %s です"

#~ msgid "Authorization check componentID is %s"
#~ msgstr "認証チェックコンポーネントIDは %s です"

#~ msgid ""
#~ "When running server in SSL mode, "
#~ "you must specify both a cert_file "
#~ "and key_file option value in your "
#~ "configuration file"
#~ msgstr "サーバーがSSLモードで動作中の場合、cert_fileおよびkey_fileオプションの値の両方を構成ファイルで指定しなければなりません"

#~ msgid "Could not bind to %s:%s after trying for 30 seconds"
#~ msgstr "30秒試みた後に%s:%s にバインドできませんでした"

#~ msgid "Starting %d workers"
#~ msgstr "%d ワーカーを開始しています"

#~ msgid "Removing dead child %s"
#~ msgstr "デッドチャイルド %s を削除しています"

#~ msgid "Not respawning child %d, cannot recover from termination"
#~ msgstr "チャイルド %s を再生成しないと、終了から回復できません"

#~ msgid "All workers have terminated. Exiting"
#~ msgstr "すべてのワーカーは終了しました。終了中"

#~ msgid "Caught keyboard interrupt. Exiting."
#~ msgstr "キーボード割り込みを受け取りました。終了中です。"

#~ msgid "Exited"
#~ msgstr "終了しました"

#~ msgid "Child %d exiting normally"
#~ msgstr "チャイルド %s 正常に終了中です"

#~ msgid "Started child %s"
#~ msgstr "チャイルド %s を開始しました"

#~ msgid "eventlet 'poll' hub is not available on this platform"
#~ msgstr "eventlet 'poll'ハブはこのプラットフォームで利用できません"

#~ msgid "Starting single process server"
#~ msgstr "シングルプロセスサーバーを開始中です"

#~ msgid "auto-creating isc registry DB"
#~ msgstr "自動作成ISCレジストリDB"

#~ msgid "not auto-creating isc registry DB"
#~ msgstr "非自動作成ISCレジストリDB"

#~ msgid "SQL connection failed. %d attempts left."
#~ msgstr "SQL接続が失敗しました。残り %d 試行。"

#~ msgid "Id not in sort_keys; is sort_keys unique?"
#~ msgstr "IDがsort_keys内にありません。sort_keysはユニークですか?"

#~ msgid "Unknown sort direction, must be 'desc' or 'asc'"
#~ msgstr "不明なソート指示です。'desc'または'asc'でなければなりません"

#~ msgid ""
#~ "get_properties_for_resource id = %s\n"
#~ " resource_id = %s\n"
#~ " name = %s\n"
#~ " type = %s\n"
#~ " value = %s"
#~ msgstr ""
#~ "get_properties_for_resource id = %s\n"
#~ " resource_id = %s\n"
#~ " name = %s\n"
#~ " type = %s\n"
#~ " value = %s"

#~ msgid ""
#~ "get_property_for_resource id = %s\n"
#~ " resource_id = %s\n"
#~ " name = %s\n"
#~ " type = %s\n"
#~ " value = %s"
#~ msgstr ""
#~ "get_property_for_resource id = %s\n"
#~ " resource_id = %s\n"
#~ " name = %s\n"
#~ " type = %s\n"
#~ " value = %s"

#~ msgid "update_resource_property %s %s %s %s"
#~ msgstr "update_resource_property %s %s %s %s"

#~ msgid "update_resource_properties %s %s"
#~ msgstr "update_resource_properties %s %s"

#~ msgid "update_resource_properties for %s %s returning %s"
#~ msgstr "update_resource_properties for %s %s returning %s"

#~ msgid "Method _delete_resource_property %s %s"
#~ msgstr "Method _delete_resource_property %s %s"

#~ msgid "Error deleting property %s %s"
#~ msgstr "プロパティ %s %s を削除中にエラーが発生しました"

#~ msgid "_delete_all_resource_properties %s"
#~ msgstr "_delete_all_resource_properties %s"

#~ msgid "delete_resource_properties %s %s"
#~ msgstr "delete_resource_properties %s %s"

#~ msgid "Upgrading database to version %s"
#~ msgstr "バージョン %s へデータベースをアップグレード中です"

#~ msgid "Downgrading database to version %s"
#~ msgstr "バージョン %s へデータベースをダウングレード中です"

#~ msgid "creating table %(table)s"
#~ msgstr "テーブル %(table)s の作成中"

#~ msgid "dropping table %(table)s"
#~ msgstr "テーブル %(table)s のドロップ中"

#~ msgid "The port on which the rabbitmq server is listening"
#~ msgstr "RabbitMQサーバーがリスンしているポート"

#~ msgid "A boolean value indicating if the selected rabbitmq server uses SSL."
#~ msgstr "選択されたRabbitMQサーバーがSSLを使用しているかどうかを示しているブーリアン値。"

#~ msgid "The user ID for authentication with rabbitmq."
#~ msgstr "RabbitMQの認証用ユーザーID。"

#~ msgid ""
#~ "The password that will be used for"
#~ " authentication with the rabbitmq server."
#~ msgstr "RabbitMQサーバーの認証で使用されるパスワード。"

#~ msgid "The virtual host used in the rabbitmq connection."
#~ msgstr "RabbitMQ接続内で使用される仮想ホスト。"

#~ msgid "Exchange name to use for connection when using rabbit strategy."
#~ msgstr "rabbitストラテジを使用した場合の接続に使用するExchange名"

#~ msgid "Topic to use for connection when using rabbit strategy."
#~ msgstr "rabbitストラテジを使用した場合の接続に使用するトピック。"

#~ msgid "The maximum number of times to attempt to connect to the AMQP server."
#~ msgstr "AMQPサーバーへの接続試行の最大回数。"

#~ msgid ""
#~ "This value multiplied by the number "
#~ "of connection attempts gives the amount"
#~ " of time in seconds to sleep "
#~ "between connection attempts to the AMQP"
#~ " server."
#~ msgstr "この値と接続試行数を掛けた値は、AMQPサーバーへの接続試行間のスリープ時間(秒)を与えます。"

#~ msgid ""
#~ "The maximum amount of time to wait"
#~ " between connection attempts.  The delay"
#~ " time will be the smaller of "
#~ "this value and the value of "
#~ "<rabbit_retry_backoff> * <the number of "
#~ "failed connection attempts so far>."
#~ msgstr ""
#~ "接続試行間で待機する最大時間。遅延時間はこの値と<rabbit_retry_backoff> * "
#~ "<これまでに失敗した接続試行数>の値のより小さなものになります。"

#~ msgid "Reconnecting to rabbitmq...topic: %s"
#~ msgstr "RabbitMQに再接続中...topic:%s"

#~ msgid "Attempting to publish message: %s"
#~ msgstr "メッセージ: %sを公開しようとしています"

#~ msgid "Message : %s has been published"
#~ msgstr "メッセージ:%s は公開されました"

#~ msgid "proc.stdout  :  %s"
#~ msgstr "proc.stdout  :%s"

#~ msgid ""
#~ "Generating certificates & configurations... "
#~ "vCenter: %s, Resource-Name: %s, ESX-"
#~ "Proxy: %s, Routing-Key: %s, Host "
#~ "IP-Address: %s"
#~ msgstr ""
#~ "証明書および構成の生成中...vCenter:%s、Resource-Name:%s、ESXプロキシ:%s"
#~ "、Routing-Key:%s、ホスト IP-Address:%s"

#~ msgid "Got neutron_password !"
#~ msgstr "neutron_passwordを受け取りました !"

#~ msgid "Rabbitmq creds created"
#~ msgstr "Rabbitmq認証情報が作成されました"

#~ msgid "All require directories created"
#~ msgstr "すべての必要なディレクトリが作成されました"

#~ msgid "Conf file written %s"
#~ msgstr "%s に書かれた構成ファイル"

#~ msgid "Compute hostname: %s"
#~ msgstr "コンピュートホスト名:%s"

#~ msgid "RabbitMQ, Postgres certs created"
#~ msgstr "RabbitMQ、Postgresの証明書が作成されました"

#~ msgid "Deleted: Rabbitmq_user = %s"
#~ msgstr "削除済み:Rabbitmq_user = %s"

#~ msgid "Creating VM...ESX-Proxy: %s, Resource: %s, vCenter: %s"
#~ msgstr "VMの作成中...ESXプロキシ:%s、リソース:%s、vCenter:%s"

#~ msgid "Writing temporary certificate...Compute node-name: %s, Config: %s"
#~ msgstr "テンポラリ証明書を書き込み中...コンピュートノード名:%s、構成:%s"

#~ msgid "Compute Certs Location: %s "
#~ msgstr "コンピュートノード証明書ロケーション:%s "

#~ msgid "unconfig cert for %s"
#~ msgstr "%s の構成されていない証明書"

#~ msgid "Setting PostgresConfig server-side config"
#~ msgstr "PostgresConfig server-side configを設定中です"

#~ msgid "Setting PostgresConfig client-side config"
#~ msgstr "PostgresConfig client-side configを設定中です"

#~ msgid "Setting RabbitMQConfig server-side config"
#~ msgstr "RabbitMQConfig server-side configを設定中です"

#~ msgid "Setting RabbitMQConfig client-side config"
#~ msgstr "RabbitMQConfig client-side configを設定中です"

#~ msgid "REQ URL: %s\n"
#~ msgstr "REQ URL:%s\n"

#~ msgid "REQ: %s\n"
#~ msgstr "REQ:%s\n"

#~ msgid "REQ BODY: %s\n"
#~ msgstr "REQ BODY:%s\n"

#~ msgid "Error in executing vshield api for rest url %s, Cause : %s"
#~ msgstr "REST URL %s でvShield APIを実行中にエラーが発生しました。原因:%s"

#~ msgid "RESP:%s\n"
#~ msgstr "RESP:%s\n"

#~ msgid "RESP BODY:%s\n"
#~ msgstr "RESP BODY:%s\n"

